import { Movie, TV } from "tmdb-ts/dist/types";

export const MOCK_MOVIES: Movie[] = [
  {
    id: 693134,
    title: "Dune: Part Two",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family.",
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "/8rpDcsfLJypbO6vREc0547VKqEv.jpg",
    release_date: "2024-02-27",
    vote_average: 8.3,
    vote_count: 5400,
    popularity: 420.5,
    adult: false,
    video: false,
    genre_ids: [878, 12],
    original_language: "en",
  },
  {
    id: 558449,
    title: "Gladiator II",
    original_title: "Gladiator II",
    overview:
      "Years after witnessing the death of the revered hero Maximus at the hands of his uncle, Lucius must enter the Colosseum after his home is conquered by tyrannical emperors.",
    poster_path: "/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg",
    backdrop_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    release_date: "2024-11-13",
    vote_average: 8.0,
    vote_count: 3200,
    popularity: 380.2,
    adult: false,
    video: false,
    genre_ids: [28, 12, 18],
    original_language: "en",
  },
  {
    id: 76600,
    title: "Avatar: The Way of Water",
    original_title: "Avatar: The Way of Water",
    overview:
      "Set more than a decade after the events of the first film, learn the story of the Sully family, the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
    poster_path: "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop_path: "/s16H6tpK2utvwDtzZ8Qy4qm5Emw.jpg",
    release_date: "2022-12-14",
    vote_average: 7.7,
    vote_count: 11000,
    popularity: 390.0,
    adult: false,
    video: false,
    genre_ids: [878, 12, 28],
    original_language: "en",
  },
  {
    id: 157336,
    title: "Interstellar",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    release_date: "2014-11-05",
    vote_average: 8.4,
    vote_count: 35000,
    popularity: 350.1,
    adult: false,
    video: false,
    genre_ids: [12, 18, 878],
    original_language: "en",
  },
  {
    id: 533535,
    title: "Deadpool & Wolverine",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary behind him. But when his homeworld faces an existential threat, Wade must team up with an even more reluctant Wolverine.",
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop_path: "/yDHYTjA3R0jFYba16jBB1jv8vCW.jpg",
    release_date: "2024-07-24",
    vote_average: 7.7,
    vote_count: 6100,
    popularity: 350.0,
    adult: false,
    video: false,
    genre_ids: [28, 35, 878],
    original_language: "en",
  },
  {
    id: 872585,
    title: "Oppenheimer",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II, exploring the moral and political consequences of mankind's deadliest invention.",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "/nb3wf9rjHGNgve9v91P9H19nMz5.jpg",
    release_date: "2023-07-19",
    vote_average: 8.1,
    vote_count: 9100,
    popularity: 310.4,
    adult: false,
    video: false,
    genre_ids: [18, 36],
    original_language: "en",
  },
  {
    id: 27205,
    title: "Inception",
    original_title: "Inception",
    overview:
      "Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: \"inception\".",
    poster_path: "/edv5CZvWj09upOsy2Y6IwDhK8bt.jpg",
    backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    release_date: "2010-07-15",
    vote_average: 8.4,
    vote_count: 36000,
    popularity: 280.0,
    adult: false,
    video: false,
    genre_ids: [28, 878, 12],
    original_language: "en",
  },
  {
    id: 155,
    title: "The Dark Knight",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    release_date: "2008-07-16",
    vote_average: 8.5,
    vote_count: 32000,
    popularity: 270.2,
    adult: false,
    video: false,
    genre_ids: [18, 28, 80, 53],
    original_language: "en",
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    original_title: "Spider-Man: Across the Spider-Verse",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    release_date: "2023-05-31",
    vote_average: 8.4,
    vote_count: 6700,
    popularity: 260.5,
    adult: false,
    video: false,
    genre_ids: [16, 28, 12, 878],
    original_language: "en",
  },
  {
    id: 299534,
    title: "Avengers: Endgame",
    original_title: "Avengers: Endgame",
    overview:
      "After the devastating events of Avengers: Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    release_date: "2019-04-24",
    vote_average: 8.3,
    vote_count: 25000,
    popularity: 250.0,
    adult: false,
    video: false,
    genre_ids: [12, 878, 28],
    original_language: "en",
  },
  {
    id: 603,
    title: "The Matrix",
    original_title: "The Matrix",
    overview:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_path: "/7u3DUTNuqWWsfHgp28dgG415y7V.jpg",
    release_date: "1999-03-30",
    vote_average: 8.2,
    vote_count: 25500,
    popularity: 240.3,
    adult: false,
    video: false,
    genre_ids: [28, 878],
    original_language: "en",
  },
  {
    id: 414906,
    title: "The Batman",
    original_title: "The Batman",
    overview:
      "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family while facing a serial killer known as the Riddler.",
    poster_path: "/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop_path: "/tRS6jvPM9qPrrnx2KRx3ew96Yot.jpg",
    release_date: "2022-03-01",
    vote_average: 7.7,
    vote_count: 9800,
    popularity: 310.0,
    adult: false,
    video: false,
    genre_ids: [80, 9648, 28],
    original_language: "en",
  },
  {
    id: 634649,
    title: "Spider-Man: No Way Home",
    original_title: "Spider-Man: No Way Home",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous.",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop_path: "/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg",
    release_date: "2021-12-15",
    vote_average: 8.0,
    vote_count: 19500,
    popularity: 360.0,
    adult: false,
    video: false,
    genre_ids: [28, 12, 878],
    original_language: "en",
  },
  {
    id: 603692,
    title: "John Wick: Chapter 4",
    original_title: "John Wick: Chapter 4",
    overview:
      "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.",
    poster_path: "/vZloFAK7NKnMGKEslUsZ2VoNmQm.jpg",
    backdrop_path: "/h8gHn0OzBoaefW7At1R5Jb3eR2U.jpg",
    release_date: "2023-03-22",
    vote_average: 7.8,
    vote_count: 6500,
    popularity: 300.0,
    adult: false,
    video: false,
    genre_ids: [28, 53, 80],
    original_language: "en",
  },
  {
    id: 475557,
    title: "Joker",
    original_title: "Joker",
    overview:
      "During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.",
    poster_path: "/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop_path: "/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    release_date: "2019-10-02",
    vote_average: 8.2,
    vote_count: 24800,
    popularity: 290.0,
    adult: false,
    video: false,
    genre_ids: [80, 53, 18],
    original_language: "en",
  },
  {
    id: 385687,
    title: "Fast X",
    original_title: "Fast X",
    overview:
      "Over many missions and against impossible odds, Dom Toretto and his family have outsmarted, out-nerved and outdriven every foe in their path. Now, they confront the most lethal opponent they've ever faced.",
    poster_path: "/fiVW06jE7z9YnO4trhaMEdclSiC.jpg",
    backdrop_path: "/4XM8DUTQb3lhLemJC51Jx4a2EuA.jpg",
    release_date: "2023-05-17",
    vote_average: 7.1,
    vote_count: 5300,
    popularity: 270.0,
    adult: false,
    video: false,
    genre_ids: [28, 80, 53],
    original_language: "en",
  },
  {
    id: 361743,
    title: "Top Gun: Maverick",
    original_title: "Top Gun: Maverick",
    overview:
      "After more than thirty years of service as one of the Navy’s top aviators, Pete 'Maverick' Mitchell is where he belongs, pushing the envelope as a courageous test pilot.",
    poster_path: "/62HCnUTziyWcpDaBO2i1DX17ljH.jpg",
    backdrop_path: "/odJ4hx6g6vBt4lBWKFD1tI8WS4x.jpg",
    release_date: "2022-05-24",
    vote_average: 8.2,
    vote_count: 8900,
    popularity: 280.0,
    adult: false,
    video: false,
    genre_ids: [28, 18],
    original_language: "en",
  },
  {
    id: 912649,
    title: "Venom: The Last Dance",
    original_title: "Venom: The Last Dance",
    overview:
      "Eddie and Venom are on the run. Hunted by both of their worlds and with the net closing in, the duo are forced into a devastating decision that will bring the curtains down on Venom and Eddie's last dance.",
    poster_path: "/aosm8Vh9ypZQZuA9AcFekLaLlRd.jpg",
    backdrop_path: "/3V4kLQg0kSqKsZiND4Jq7mB9tq1.jpg",
    release_date: "2024-10-22",
    vote_average: 6.8,
    vote_count: 2600,
    popularity: 340.0,
    adult: false,
    video: false,
    genre_ids: [28, 878, 12],
    original_language: "en",
  },
  {
    id: 945961,
    title: "Alien: Romulus",
    original_title: "Alien: Romulus",
    overview:
      "While scavenging the deep ends of a derelict space station, a group of young space colonizers come face to face with the most terrifying life form in the universe.",
    poster_path: "/b33nnKl1vvg6AqICagJW9Sil4K.jpg",
    backdrop_path: "/9SSEUrSqhljBMzRe4aBTh17r0aC.jpg",
    release_date: "2024-08-13",
    vote_average: 7.2,
    vote_count: 3100,
    popularity: 310.0,
    adult: false,
    video: false,
    genre_ids: [27, 878],
    original_language: "en",
  },
];

export const MOCK_TV_SHOWS: TV[] = [
  {
    id: 66732,
    name: "Stranger Things",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    first_air_date: "2016-07-15",
    vote_average: 8.6,
    vote_count: 17000,
    popularity: 450.2,
    adult: false,
    genre_ids: [18, 9648, 10765],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 1399,
    name: "Game of Thrones",
    original_name: "Game of Thrones",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    first_air_date: "2011-04-17",
    vote_average: 8.4,
    vote_count: 23000,
    popularity: 430.0,
    adult: false,
    genre_ids: [10765, 18, 10759],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 100088,
    name: "The Last of Us",
    original_name: "The Last of Us",
    overview:
      "Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone.",
    poster_path: "/d5NXSklXo0qyIYkgV94XAgMIckC.jpg",
    backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
    first_air_date: "2023-01-15",
    vote_average: 8.6,
    vote_count: 5200,
    popularity: 410.2,
    adult: false,
    genre_ids: [18, 10759],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 119051,
    name: "Wednesday",
    original_name: "Wednesday",
    overview:
      "Wednesday Addams' misadventures as a student at Nevermore Academy: a very unique boarding school in New England.",
    poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
    backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
    first_air_date: "2022-11-23",
    vote_average: 8.4,
    vote_count: 8200,
    popularity: 370.0,
    adult: false,
    genre_ids: [10765, 9648, 35],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 93405,
    name: "Squid Game",
    original_name: "오징어 게임",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits — with deadly high stakes.",
    poster_path: "/dDlEmu3EZ0Pgg93K2SVNLCjCSvE.jpg",
    backdrop_path: "/2meX1nMdScFOoV4370rqHWFDxZq.jpg",
    first_air_date: "2021-09-17",
    vote_average: 8.2,
    vote_count: 14000,
    popularity: 360.5,
    adult: false,
    genre_ids: [18, 9648, 10759],
    original_language: "ko",
    origin_country: ["KR"],
  },
  {
    id: 1396,
    name: "Breaking Bad",
    original_name: "Breaking Bad",
    overview:
      "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He chooses to enter a dangerous world of prescription drugs and crime.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP19.jpg",
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 14500,
    popularity: 340.0,
    adult: false,
    genre_ids: [18, 80],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 71912,
    name: "The Witcher",
    original_name: "The Witcher",
    overview:
      "Geralt of Rivia, a mutated monster-hunter for hire, journeys toward his destiny in a turbulent world where people often prove more wicked than beasts.",
    poster_path: "/7vjaCdMw15FEbDYMov6buEJIRZr.jpg",
    backdrop_path: "/jBJWaqoSCiARWtfV0GlqHrcdidd.jpg",
    first_air_date: "2019-12-20",
    vote_average: 8.0,
    vote_count: 5800,
    popularity: 295.0,
    adult: false,
    genre_ids: [10765, 18, 10759],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 94997,
    name: "House of the Dragon",
    original_name: "House of the Dragon",
    overview:
      "The Targaryen dynasty is at the absolute apex of its power, with more than 15 dragons under their yoke. Most empires crumble from such heights; in the case of the Targaryens, their slow fall begins when King Viserys breaks with a century of tradition by naming his daughter Rhaenyra heir to the Iron Throne.",
    poster_path: "/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg",
    backdrop_path: "/etjA69A2CSv2YAMjL8r7cAB5Zg.jpg",
    first_air_date: "2022-08-21",
    vote_average: 8.4,
    vote_count: 4600,
    popularity: 280.0,
    adult: false,
    genre_ids: [10765, 18, 10759],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 94605,
    name: "Arcane",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.",
    poster_path: "/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg",
    backdrop_path: "/uLOmOF5hw7gSjKqfAg7QhJ7j44W.jpg",
    first_air_date: "2021-11-06",
    vote_average: 8.7,
    vote_count: 4100,
    popularity: 260.0,
    adult: false,
    genre_ids: [16, 10765, 18, 10759],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 70523,
    name: "Dark",
    original_name: "Dark",
    overview:
      "A missing child causes four families to help each other for answers. What they could not imagine is that this mystery may be connected to countless other secrets of the small town.",
    poster_path: "/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg",
    backdrop_path: "/3lBDg3i6nnOccR58T3YtFkK4c0f.jpg",
    first_air_date: "2017-12-01",
    vote_average: 8.5,
    vote_count: 6500,
    popularity: 250.0,
    adult: false,
    genre_ids: [10765, 9648, 18],
    original_language: "de",
    origin_country: ["DE"],
  },
  {
    id: 76479,
    name: "The Boys",
    original_name: "The Boys",
    overview:
      "A fun and irreverent take on what happens when superheroes, who are as popular as celebrities, as influential as politicians and as revered as gods, abuse their superpowers rather than use them for good.",
    poster_path: "/2zmTngzbOHQqWvzqiqWbk29x10S.jpg",
    backdrop_path: "/nGsNiavITtxw31btDg5JJnv9G5z.jpg",
    first_air_date: "2019-07-25",
    vote_average: 8.5,
    vote_count: 10000,
    popularity: 240.0,
    adult: false,
    genre_ids: [10765, 10759],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 71446,
    name: "Money Heist",
    original_name: "La Casa de Papel",
    overview:
      "To carry out the biggest heist in history, a mysterious man called The Professor recruits a band of eight robbers who have a single characteristic: none of them has anything to lose.",
    poster_path: "/reEMJA1uzscCbk5rUhGnyRYEvqp.jpg",
    backdrop_path: "/gFZriCkpJYsApP02URCj3Q0z4wF.jpg",
    first_air_date: "2017-05-02",
    vote_average: 8.3,
    vote_count: 18000,
    popularity: 320.0,
    adult: false,
    genre_ids: [80, 18],
    original_language: "es",
    origin_country: ["ES"],
  },
  {
    id: 60574,
    name: "Peaky Blinders",
    original_name: "Peaky Blinders",
    overview:
      "A gangster family epic set in 1919 Birmingham, England and centered on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby.",
    poster_path: "/vUUqzWa2LnHIVqkaKVlVGkVcZIW.jpg",
    backdrop_path: "/2UG177tWHy7xRmtKWuhmgNWGQjk.jpg",
    first_air_date: "2013-09-12",
    vote_average: 8.5,
    vote_count: 9200,
    popularity: 290.0,
    adult: false,
    genre_ids: [18, 80],
    original_language: "en",
    origin_country: ["GB"],
  },
  {
    id: 63174,
    name: "Lucifer",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker.",
    poster_path: "/ekZobS2isE6mA53RAiGDG93hBxL.jpg",
    backdrop_path: "/ta5oblHGzbSBMKSud5wrWgwEbDx.jpg",
    first_air_date: "2016-01-25",
    vote_average: 8.4,
    vote_count: 14000,
    popularity: 260.0,
    adult: false,
    genre_ids: [80, 10765],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 84958,
    name: "Loki",
    original_name: "Loki",
    overview:
      "After stealing the Tesseract during the events of Avengers: Endgame, an alternate version of Loki is brought to the mysterious Time Variance Authority (TVA).",
    poster_path: "/voHUmltYmKyleukbtqA63vs9IRm.jpg",
    backdrop_path: "/9zIq5i643B8gZk6j5Wv6u4xYn3S.jpg",
    first_air_date: "2021-06-09",
    vote_average: 8.2,
    vote_count: 11000,
    popularity: 240.0,
    adult: false,
    genre_ids: [18, 10765],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 82856,
    name: "The Mandalorian",
    original_name: "The Mandalorian",
    overview:
      "After the stories of Jango and Boba Fett, another warrior emerges in the Star Wars universe. The Mandalorian is set after the fall of the Empire and before the emergence of the First Order.",
    poster_path: "/eU1i6eHXlzMOlEq0ku1R07Y9WTV.jpg",
    backdrop_path: "/9ijMGlJKqcslswWUzTEwScm82Gs.jpg",
    first_air_date: "2019-11-12",
    vote_average: 8.4,
    vote_count: 9500,
    popularity: 230.0,
    adult: false,
    genre_ids: [10765, 10759, 18],
    original_language: "en",
    origin_country: ["US"],
  },
  {
    id: 1429,
    name: "Attack on Titan",
    original_name: "進撃の巨人",
    overview:
      "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction.",
    poster_path: "/hTP1dtwGFamzeL2V9Gtwsqx4pXd.jpg",
    backdrop_path: "/rqbCbjB19amtOtFQbb3K2lgm2zv.jpg",
    first_air_date: "2013-04-07",
    vote_average: 8.7,
    vote_count: 6100,
    popularity: 220.0,
    adult: false,
    genre_ids: [16, 10759, 10765],
    original_language: "ja",
    origin_country: ["JP"],
  },
  {
    id: 85937,
    name: "Demon Slayer: Kimetsu no Yaiba",
    original_name: "鬼滅の刃",
    overview:
      "It is the Taisho Period in Japan. Tanjiro, a kindhearted boy who sells charcoal for a living, finds his family slaughtered by a demon. To make matters worse, his younger sister Nezuko has been transformed into a demon.",
    poster_path: "/xUfRZu2mi8jH6SzQEJGP6tjBuYj.jpg",
    backdrop_path: "/nTvM4mhqZlHIvUkI1gVnWumXP7E.jpg",
    first_air_date: "2019-04-06",
    vote_average: 8.7,
    vote_count: 6300,
    popularity: 215.0,
    adult: false,
    genre_ids: [16, 10759, 10765],
    original_language: "ja",
    origin_country: ["JP"],
  },
  {
    id: 2190,
    name: "One Piece",
    original_name: "ONE PIECE",
    overview:
      "Years ago, the fearsome 'Pirate King', Gol D. Roger was executed leaving behind a huge cache of riches and the famed 'One Piece' treasure. Monkey D. Luffy sets out to become the new Pirate King.",
    poster_path: "/fcXdJlbSdUEeMSJFsXKsznGwwok.jpg",
    backdrop_path: "/4MCKNAc6AbWjEsM2h9Xc29owo4z.jpg",
    first_air_date: "1999-10-20",
    vote_average: 8.7,
    vote_count: 4500,
    popularity: 210.0,
    adult: false,
    genre_ids: [16, 10759, 35],
    original_language: "ja",
    origin_country: ["JP"],
  },
  {
    id: 42009,
    name: "Black Mirror",
    original_name: "Black Mirror",
    overview:
      "Over the last ten years, technology has transformed almost every aspect of our lives before we've had time to stop and question it. In every home; on every desk; in every palm; Black Mirror reflects our 21st Century unease with the modern world.",
    poster_path: "/7RwAOiZ38734hY8YqXgH31T0cvy.jpg",
    backdrop_path: "/1r90tOqD8nflP1x5X7k3W5G8F5Z.jpg",
    first_air_date: "2011-12-04",
    vote_average: 8.3,
    vote_count: 5100,
    popularity: 200.0,
    adult: false,
    genre_ids: [10765, 18, 9648],
    original_language: "en",
    origin_country: ["GB"],
  },
];
